### ISSUE TITLE
Update service endpoint for INGV 

### ISSUE THREAD

**Issue by petrrr** [crotwell/fdsn-service-check#15]
The test still seem to use a deprecated services endpoint URL (~~webservices.rm.ingv.it~~). 

Please update to the preferred / official service endpoint URL: `webservices.ingv.it` as published on http://www.fdsn.org/webservices/datacenters/.

**Comment by crotwell** [comment]
Fixed in https://github.com/crotwell/fdsn-service-check/commit/786083e436c63fcfdc8a5b7a92f39e889823f263

Thanks for letting me know. All of this predated the new data center registry and I have not upgraded it to make use of it.
