### ISSUE TITLE
Geonet data

### ISSUE THREAD

**Issue by rauwitt** [crotwell/fdsn-service-check#20]
As Geonet has updated their FDSN-webservice their data could b added to the service-check:
https://www.geonet.org.nz/data/access/FDSN

**Comment by crotwell** [comment]
I have added service.geonet.org.nz, however all tests are failing due to missing CORS headers.

For example,in the browser console when loading http://service.geonet.org.nz/fdsnws/event/1/version via javascript:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://service.geonet.org.nz/fdsnws/dataselect/1/version. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.
```

More information here:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by rauwitt** [comment]
Thank you, Mr. Crotwell,

 

for adding GEONET to the service check.

 

I thought to ask GEONET if they can add missing CORS headers,

but I presume they won't.

 

Regards,

Raúl Witthüser


 
 

Gesendet: Dienstag, 01. August 2023 um 16:01 Uhr
Von: "Philip Crotwell" ***@***.***>
An: "crotwell/fdsn-service-check" ***@***.***>
Cc: "rauwitt" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [crotwell/fdsn-service-check] Geonet data (Issue #20)


 

I have added service.geonet.org.nz, however all tests are failing due to missing CORS headers.

For example,in the browser console when loading http://service.geonet.org.nz/fdsnws/event/1/version via javascript:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://service.geonet.org.nz/fdsnws/dataselect/1/version. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.


More information here:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by crotwell** [comment]
I have updated the fdsn web service check to make use of the FDSN datacenter registry,
https://www.fdsn.org/datacenters/
so only datacenters registered there will be shown. 

This is better in the long term as updates happen automatically, but likely will cause GEONET to disappear as they do not seem to be in the registry yet. 

I filed a bug with them:
https://github.com/GeoNet/fdsn/issues/136
